FROM vernemq/vernemq:1.12.3

LABEL maintainer="Domenico Briganti <domenico.briganti@kalpa.it>"

ENV DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT on
ENV DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT on
ENV DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT on 
ENV DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT on
ENV DOCKER_VERNEMQ_ALLOW_ANONYMOUS on
ENV DOCKER_VERNEMQ_LOG__CONSOLE console

COPY startup.sh   /startup.sh

USER root

RUN chmod +x /startup.sh

USER vernemq

CMD ["/startup.sh"]